log-dir = "~/junk/snoopy-logs"  # usually "/var/log"
collation-dir = "~/junk/snoopy-logs/collated"

[class.bifo.exclude]
yum-repo = [
    "anaconda",
    "base",
    "centos7-os",
    "centos7-updates",
    "epel",
    "epel7",
    "updates",
]

rpm = [
    "util-linux",
]

[class.bifo.include]
rpm = [
    "R-core",
]
